// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm665qj_jSP8UaoSmN3Xa-ZbgTGa5OkkY',
    appId: '1:862790190090:android:3a280ab8a2bb96728acbf3',
    messagingSenderId: '862790190090',
    projectId: 'classtrack-49bbe',
    storageBucket: 'classtrack-49bbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoZMZc7uZS9JYAw-GfienHEMAHp5Cb6I',
    appId: '1:862790190090:ios:f41fa899d535d9c08acbf3',
    messagingSenderId: '862790190090',
    projectId: 'classtrack-49bbe',
    storageBucket: 'classtrack-49bbe.firebasestorage.app',
    iosBundleId: 'com.example.newprpoject1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-HNH8r_qTClceZgLrV1dogYIVLKb6Ldw',
    appId: '1:862790190090:web:2252c6a3ce51f14b8acbf3',
    messagingSenderId: '862790190090',
    projectId: 'classtrack-49bbe',
    authDomain: 'classtrack-49bbe.firebaseapp.com',
    storageBucket: 'classtrack-49bbe.firebasestorage.app',
    measurementId: 'G-HMRQBNWQWG',
  );

}